### ISSUE TITLE
Multiple commits since last update site are not obvious

### ISSUE THREAD

**Issue by bryan-strassner** [att-comdev/shipyard#16]
When multiple configdocs commits have been done since the last deployment, there is no ready means to determine what's being done to the site. Shipyard should:
1. reject deploy site or update site requests that have had multiple commits since the last site true-up action. An option to override this guard should be allowed for the actions in the form of a parameter to the action.
2. The configdocs API should provide a way to see what's been changed since the last site true-up, not just the last commit of configdocs. This might be accommodated by new deckhand tags like the 'commit' tag, but for 'site true-up' or similar applied by the deploy and update site commands.

**Comment by codebind-luna** [comment]
has someone already implemented this?

**Comment by bryan-strassner** [comment]
Yes, this is already implemented with commit id d3d3a0ecb7041ebd38251ebdaeebd6a70045399c.
Thanks and sorry the issue wasn't closed then.
