### ISSUE TITLE
database upgrade/downgrade needs to be exposed as new entrypoints

### ISSUE THREAD

**Issue by bryan-strassner** [att-comdev/shipyard#17]
Instead of happening as part of every startup of Shipyard, the alembic commands to upgrade and downgrade need to be exposed as entrypoints.
Upgrade should default upgrade to latest
Downgrade should require a target version
The helm chart should include the upgrade as part of the db init job that runs upon deployment.
The alembic upgrade that happens as part of startup (and the associated option) needs to be removed.

This will lead to less concern about scaling out multiple replicas of Shipyard vying for doing the upgrade/checking for upgrade needs.

**Comment by krystaknight** [comment]
I'll take this one

**Comment by bryan-strassner** [comment]
Restructuring was completed earlier this year to support this. Commit ID 7fbc3dad25c92cdc2b6474619773f6cd05c4f926
Actual downgrade support may come at a later time.
