### ISSUE TITLE
Improve ingress controller handling in deckhand_load_yaml script

### ISSUE THREAD

**Issue by craiganderson** [att-comdev/shipyard#18]
Currently the deckhand_load_yaml.sh script does not check that the `ingress_controller_ip` returned a non-null value, which may result in invalid entries written to /etc/hosts.

Also, the subsequent DNS entries written to /etc/hosts are not idempotent, so script re-runs (e.g., after discovering and resolving YAML validation errors) will result in duplicate (and possibly disagreeing) DNS entries written to /etc/hosts.

**Comment by craiganderson** [comment]
The --replace flag should also be used in the "shipyard create configdocs" command, to allow for iterative YAML corrections and re-execution of this script to get past validation errors.

**Comment by eanylin** [comment]
Issues will be addressed by https://review.gerrithub.io/#/c/396340/

**Comment by eanylin** [comment]
The p.s. has been reviewed and merged. This issue will be closed.
